"""Bring-your-own-logic: no LLM at all.

The response is generated by a plain decision tree over the transcript. The
point of the SDK is that `on_response` can do *anything* — an open-source
model, a rules engine, a lookup table — and the voice layer never knows the
difference because the seam is just the OpenAI schema.

    python examples/decision_tree.py
"""

from assembly_agent import Agent

agent = Agent(name="Pizza Line", voice="ivy", greeting="Pizza line, what can I get started for you?")

MENU = {"margherita": 12, "pepperoni": 14, "veggie": 13}


@agent.on_response
async def respond(ev, ctx):
    text = ev.text.lower()
    order = ctx.get("order", [])

    if "menu" in text:
        items = ", ".join(f"{name} for {price} dollars" for name, price in MENU.items())
        return f"We've got {items}. What sounds good?"

    for name, price in MENU.items():
        if name in text:
            order.append((name, price))
            ctx.set("order", order)
            return f"Added a {name}. Anything else?"

    if "that's it" in text or "checkout" in text:
        total = sum(p for _, p in order)
        names = ", ".join(n for n, _ in order) or "nothing yet"
        return f"That's {names}, for a total of {total} dollars. We'll have it ready in twenty minutes."

    return "Sorry, I didn't catch that. You can ask for the menu or name a pizza."


if __name__ == "__main__":
    agent.serve()
